jobs:
- job: Create_Windows_2019_Azure_RDP_by_TinHocThucHanh
  pool:
    vmImage: windows-latest
  steps:
   - checkout: none 
   - script: |
       echo ngrok authtoken "1iJVkNi9DF7DITjSw8r5PW0cBtl_2ti8jPfuGHYUf1qAmYXkk" > NGROK.bat
       curl -s -O https://raw.githubusercontent.com/eweiss2021/Azure_RDP/main/AzureNgrokAutoRegion.bat
       AzureNgrokAutoRegion.bat
     displayName: 'Run RDP Hack on Azure Pipeline'
